services:

  Lle\CruditBundle\Brick\ListBrick\ListFactory:
    arguments: ['@Lle\CruditBundle\Resolver\RessourceResolver', '@request_stack']
    tags: [ 'crudit.brick' ]

  Lle\CruditBundle\Brick\ShowBrick\ShowFactory:
    arguments: ['@Lle\CruditBundle\Resolver\RessourceResolver', '@request_stack']
    tags: [ 'crudit.brick' ]

  Lle\CruditBundle\Brick\FormBrick\FormFactory:
    arguments: ['@Lle\CruditBundle\Resolver\RessourceResolver', '@request_stack', '@form.factory']
    tags: [ 'crudit.brick' ]

  Lle\CruditBundle\Brick\LinksBrick\LinksFactory:
    arguments: ['@Lle\CruditBundle\Resolver\RessourceResolver', '@request_stack']
    tags: [ 'crudit.brick' ]
