services:
    Lle\CruditBundle\Form\Type\AutocompleteType:
        tags: [ form.type ]
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
    Lle\CruditBundle\Form\DataTransformer\EntityToIdTransformer:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
    Lle\CruditBundle\Service\GedmoTranslatableFieldManager:
        arguments:
            - "@doctrine.orm.entity_manager"
    Lle\CruditBundle\Form\Type\GedmoTranslatableType:
        arguments:
            - '%kernel.default_locale%'
            - '%kernel.enabled_locales%'
            - '@Lle\CruditBundle\Service\GedmoTranslatableFieldManager'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
        tags:
            - { name: form.type, alias: lego_gedmo_translatable }
    Lle\CruditBundle\Form\Type\MarkdownType:
        autowire: true
        tags:
            - { name: form.type, alias: crudit_markdown }
    Lle\CruditBundle\Form\Type\GroupType:
        autowire: true
        tags:
            - { name: form.type, alias: crudit_group }
    Lle\CruditBundle\Form\Type\FileType:
        autowire: true
        tags:
            - { name: form.type, alias: crudit_file }
    Lle\CruditBundle\Form\Extension\TooltipExtension:
        tags:
            - { name: form.type_extension }
