services:
    Lle\CruditBundle\Form\Type\AutocompleteType:
        tags: [ form.type ]
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
    Lle\CruditBundle\Form\DataTransformer\EntityToIdTransformer:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
    Lle\CruditBundle\Service\GedmoTranslatableFieldManager:
        arguments:
            - "@doctrine.orm.entity_manager"
    Lle\CruditBundle\Form\Type\GedmoTranslatableType:
        arguments:
            - '%php_translation.default_locale%'
            - '%php_translation.locales%'
            - '@Lle\CruditBundle\Service\GedmoTranslatableFieldManager'
            - '@Symfony\Contracts\Translation\TranslatorInterface'
        tags:
           - { name: form.type, alias: lego_gedmo_translatable }
