services:
    Lle\CruditBundle\Form\Type\AutocompleteType:
        tags: [ form.type ]
        arguments:
            - "@router"
            - "@Lle\\CruditBundle\\Form\\DataTransformer\\EntityToIdTransformer"
            - "@doctrine.orm.entity_manager"
    Lle\CruditBundle\Form\DataTransformer\EntityToIdTransformer:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"