services:
  Lle\CruditBundle\EventListener\KernelControllerListener:
    arguments: ['@twig', '@Lle\CruditBundle\Provider\LayoutProvider', '@Lle\CruditBundle\Provider\ConfigProvider', '@controller_resolver']
    tags:
      - { name: kernel.event_listener, event: kernel.controller }
